# Generated by Django 4.2.10 on 2025-12-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AddField(
            model_name='profile',
            name='primary_role',
            field=models.CharField(choices=[('admin', 'admin'), ('trainer', 'trainer'), ('manager', 'manager'), ('trainee', 'trainee')], db_column='primary_role', default='trainee', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image_url',
            field=models.TextField(blank=True, db_column='profile_image_url', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='profile',
            table='users',
        ),
    ]
