# Generated by Django 4.2.10 on 2025-12-30 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_create_authtoken_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.RemoveField(
            model_name='course',
            name='certificate_enabled',
        ),
        migrations.RemoveField(
            model_name='course',
            name='completion_rule',
        ),
        migrations.RemoveField(
            model_name='course',
            name='language',
        ),
        migrations.RemoveField(
            model_name='course',
            name='sequential_access',
        ),
        migrations.RemoveField(
            model_name='course',
            name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='course',
            name='visibility',
        ),
        migrations.AddField(
            model_name='course',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(default='self_paced', max_length=30),
        ),
        migrations.AddField(
            model_name='course',
            name='estimated_duration_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_mandatory',
            field=models.BooleanField(db_column='is_mandatory', default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='outcomes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='passing_criteria',
            field=models.IntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='id',
            field=models.UUIDField(db_column='assignment_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='unit',
            field=models.OneToOneField(db_column='module_id', on_delete=django.db.models.deletion.CASCADE, related_name='assignment_details', to='courses.unit'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='created_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.UUIDField(db_column='course_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_staff',
            field=models.BooleanField(db_column='is_staff', default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_superuser',
            field=models.BooleanField(db_column='is_superuser', default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(db_column='password_hash', max_length=255),
        ),
        migrations.AlterField(
            model_name='unit',
            name='course',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='id',
            field=models.UUIDField(db_column='module_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
