# Generated by Django 4.2 on 2025-12-31 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_update_module_type_check'),
        ('courses', '0008_update_module_type_check'),
    ]

    operations = [
    ]
